### PR TITLE
Make plugin compatible with Matomo 3.8 which changes UsersManager.updateUser

### PR DESCRIPTION
**Pull request by tsteur**
refs https://github.com/matomo-org/matomo/pull/13683

### CODE REVIEW

**Comment by tsteur** [comment]
@mattab I'd create a new release with this change and then when the next beta is out, people will be able to upgrade to it... until then users will only see the update is available but because the beta is not out yet, not be able to upgrade yet...

could also wait for a week or two and release it later... it'll only break the password update functionality (since it now requires to enter a password)

**Comment by mattab** [comment]
@tsteur sounds good, can you create the release? Does this need further testing prior?

**Comment by tsteur** [comment]
@mattab might be good if possible, I'm quite confident it works otherwise. Tried with couple changes to make the tests work but couldn't. There is one failing test and I can't run the tests locally https://travis-ci.org/matomo-org/plugin-LoginLdap/jobs/470735622#L1201

**Comment by diosmosis** [comment]
@tsteur the test failure is because the wrong password is being used in that test, the code has Fixture::ADMIN_USER_PASSWORD, but right above it the user is created w/ the password `'thispasswordwillbechanged'`.

**Comment by diosmosis** [comment]
`updateUser` is also called in UserSynchronizer, will update myself in a bit.

**Comment by tsteur** [comment]
@diosmosis it needs the password of the currently logged in user ... not sure what this is in the tests?

**Comment by diosmosis** [comment]
Oh right, forgot about that. I'll see if I can fix the build.

**Pull request merged**
